name: deploytoheroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ขั้นตอนใหม่: ติดตั้ง Heroku CLI
      - uses: heroku/setup-heroku@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      # ขั้นตอนเดิม: Deploy ไปยัง Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true